### ISSUE TITLE
Feature request: authentication via JWT token

### ISSUE THREAD

**Issue by marcoancona** [braintrustdata/braintrust-proxy#105]
We are looking for a proxy AI API that we can call from client code. Since credentials on the client cannot be protected, it would be great if the proxy could accept a user JWT token with limited availability and verify the valid of the token with a provided secret before proceeding with the request.

Ideally, the user id contained in the JWT is logged to be able to monitor how many requests each user generates and prevent abuse.

**Comment by kevin1** [comment]
Hi @marcoancona, I've added an endpoint that issues temporary credentials in the JWT format. PR linked above and the documentation is here: https://www.braintrust.dev/docs/guides/proxy#temporary-credentials-for-end-user-access

Please let me know what you think!
