### ISSUE TITLE
Encrypt vector embeddings

### ISSUE THREAD

**Issue by morgante** [braintrustdata/braintrust-proxy#44]
In my reading of the source code, it looks like vector embeddings are not currently encrypted. This is potentially problematic, since they are (somewhat) reversible.

Would you be open to a pull request to encrypt content using the input, so it's only retrievable when you have access to the original source text?

**Comment by ankrgyl** [comment]
Hi @morgante! Thanks for the report. Yes, definitely open to a PR. I'm not totally clear on where you'd want them to be encrypted that they are not (e.g. the results cache should cache the ouput), but a PR would help clarify!

**Comment by morgante** [comment]
Great. Specifically, I don't want the embedding to be retrievable unless you have the original input chunk. I'll put together a PR.

**Comment by ankrgyl** [comment]
Ok got it! I believe that to currently be the case, but I am likely missing something you're observing. Looking forward to the PR.
